---
- hosts: all
  become: yes
  tasks:
   - name: Install apache
     yum:
        name: httpd
        state: present
   - name: start the service
     service: 
        name: httpd
        state: started

     