---
- name: Create an EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: id_rsa
    instance_type: t2.micro
    image: ami-0080e4c5bc078760e
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{image}}"
         wait: true
         region: "{{region}}"
         aws_access_key: AKIAIZYZNDJVGGZLVCJQ
         aws_secret_key: 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
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2
    - name: Get theh Ip address
      debug: var=ec2.instances[0].public_dns_name

    - pause: minutes=1
