---
- hosts: windows
  tasks:
  - name: install IIS
    win_feature:
      name: Web-Server
      state: present
    when: ansible_os_family == "Windows"

  - name: Deploy index file
    template:
      src: iisstart.j2
      dest: c:\inetpub\wwwroot\issstart.htm